base/urls.py
from django.urls import path

from base.views import ClientList, ClientUpdate, RoutList, RoutUpdate, change_service_company

app_name = 'base'

urlpatterns = [
    path('change-service-company/<int:pk>/', change_service_company, name='change-service-company'),

    # Контрагенты
    path('reference_books/clients/<int:pk>/update/', ClientUpdate.as_view(), name='upd-client'),
    path('reference_books/clients/', ClientList.as_view(), name='getlist-clients'),

    # Маршруты
    path('reference_books/routs/<int:pk>/update/', RoutUpdate.as_view(), name='upd-rout'),
    path('reference_books/routs/', RoutList.as_view(), name='getlist-routs'),
]

helpdesk/urls.py
from django.contrib import admin
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path, reverse_lazy, include
from django.conf import settings
from django.conf.urls.static import static

from base.views import *

urlpatterns = [
    path('admin/', admin.site.urls),

    path(r'accounts/login/', CustomLoginPage.as_view(), name='login'),
    path('accounts/logout', LogoutView.as_view(next_page=reverse_lazy('login')), name='logout'),
    # path('accounts/profile/', , name='profile'),

    # path('finder/', advanced_finder, name='advanced-finder'),

    path('base/', include('base.urls', namespace='base')),

    path('exploitation/', include('exploitation.urls', namespace='exploitation')),
    path('build/', include('build.urls', namespace='build')),
    path('maintenance/', include('maintenance.urls', namespace='maintenance')),

    path('', dashboard, name='dashboard'),
]

maintenance/urls.py
__author__ = 'ipman'

from django.urls import path

from maintenance.views import *

app_name = 'maintenance'

urlpatterns = [
    # Просмотреть объект
    path('objects/<int:pk>/detail/', MaintenanceObjectDetail.as_view(), name='view-object'),
    # Просмотреть заявку
    path('item/<int:pk>/detail/', MaintenanceProposalDetail.as_view(), name='view-proposal'),
    # Обновить заявку
    path('item/<int:pk>/update/', MaintenanceProposalUpdate.as_view(), name='upd-manage-proposal'),
    # Вывести список заявок
    path('objects/<slug:status>/', MaintenanceObjectList.as_view(), name='getlist-objects'),
    path('proposal/<slug:status>/', MaintenanceProposalList.as_view(), name='getlist-proposals'),
]

templates/templatetags/build_request_add.html
{% load django_bootstrap5 %}

<div class="modal fade" id="newProposal" tabindex="-1" aria-labelledby="newProposalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="newProposalLabel">Новая заявка</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <div class="modal-body">
                    <div class="mb-3">
                        <div class="row">
                            <div class="col-4">
                                {% bootstrap_label "Тип" label_for="type_build" %}*
                            </div>
                            <div class="col-8">
                                {% bootstrap_field form.type_build layout='inline' %}
                            </div>
                        </div>
                    </div>
                    <div class="mb-3">
                        <div class="row">
                            <div class="col-4">
                                {% bootstrap_label "Конфигурация системы охраны" label_for="type_security" %}*
                            </div>
                            <div class="col-8">
                                {% bootstrap_field form.type_security layout='inline' %}
                            </div>
                        </div>
                    </div>
                    <div class="mb-3">
                        <div class="row">
                            <div class="col-4">
                                {% bootstrap_label "Контрагент" label_for="object_number" %}*
                            </div>
                            <div class="col-8">
                                {% bootstrap_field form.client_words layout='inline' %}
                            </div>
                            <div class="col-8 mt-4 offset-4">
                                {% bootstrap_field form.client_choices layout='inline' %}
                            </div>
                        </div>
                    </div>
                    <div class="mb-3">
                        <div class="row">
                            <div class="col-4">
                                {% bootstrap_label "Объект" label_for="object_number" %}*
                            </div>
                            <div class="col-8">
                                {% bootstrap_field form.object_address layout='inline' %}
                            </div>
                        </div>
                    </div>
                    <div class="mb-3">
                        <div class="row">
                            <div class="col-4">
                                {% bootstrap_label "Задача" label_for="descript_task" %}*
                            </div>
                            <div class="col-8">
                                {% bootstrap_field form.descript_task layout='inline' %}
                            </div>
                        </div>
                    </div>
                    <div class="mb-3">
                        <div class="row">
                            <div class="col-4">
                                {% bootstrap_label "Выполнить" label_for="date_schedule" %}*
                            </div>
                            <div class="col-8">
                                {% bootstrap_field form.date_schedule layout='inline' %}
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Закрыть</button>
                <button type="submit" class="btn btn-primary">Создать запись</button>
            </div>
        </div>
    </div>
</div>

templates/templatetags/client_add.html
{% load django_bootstrap5 %}

<div class="modal fade" id="newClient" tabindex="-1" aria-labelledby="newClientLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="newProposalLabel">Новый контрагент </h5>
            </div>
            <div class="modal-body">
                <div class="modal-body">
                    <div class="mb-3">
                        <div class="row">
                            <div class="col-4">
                                {% bootstrap_label "Тип контрагента" label_for="descript_trouble" %}*
                            </div>
                            <div class="col-8">
                                {% bootstrap_field form.type layout='inline' %}
                            </div>
                        </div>
                    </div>
                    <div class="mb-3">
                        <div class="row">
                            <div class="col-4">
                                {% bootstrap_label "Наименование" label_for="object_number" %}*
                            </div>
                            <div class="col-3">
                                {% bootstrap_field form.name layout='inline' %}
                            </div>
                        </div>
                    </div>
                    <div class="mb-3">
                        <div class="row">
                            <div class="col-4">
                                {% bootstrap_label "ИНН/КПП" label_for="coworkers" %}
                            </div>
                            <div class="col-4">
                                {% bootstrap_field form.inn layout='inline' %}
                            </div>
                            <div class="col-4">
                                {% bootstrap_field form.kpp layout='inline' %}
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Закрыть</button>
                <button type="submit" class="btn btn-primary">Создать запись</button>
            </div>
        </div>
    </div>
</div>

templates/templatetags/dashboard_card_build.html
<div class="card info-card revenue-card">
    <div class="card-body">
        <h5 class="card-title">Монтаж/Демонтаж <span>| В работе</span></h5>
        <div class="d-flex align-items-center">
            <div class="card-icon rounded-circle d-flex align-items-center justify-content-center">
                <i class="ri-hammer-line"></i>
            </div>
            <div class="ps-3">
                <h6>{% if proposals_isshedule_today > 0 %}{{ proposals_iscomplete }}{% else %}Нет данных{% endif %}</h6>
                <span class="text-success small pt-1 fw-bold">{% if proposals_isshedule_today > 0 %}{{ percent_iscomplete }}%</span>
                <span class="text-muted small pt-2 ps-1">от запланированных {{ proposals_isshedule_today }}{% endif %}</span>
            </div>
        </div>
    </div>
</div>

templates/templatetags/dashboard_card_maintenance.html
<div class="card info-card customers-card">
    <div class="card-body">
        <h5 class="card-title">Техническое обслуживание <span>| В работе</span></h5>
        <div class="d-flex align-items-center">
            <div class="card-icon rounded-circle d-flex align-items-center justify-content-center">
                <i class="ri-tools-line"></i>
            </div>
            <div class="ps-3">
                <h6>{% if proposals_isshedule_today > 0 %}{{ proposals_iscomplete }}{% else %}Нет данных{% endif %}</h6>
                <span class="text-success small pt-1 fw-bold">{% if proposals_isshedule_today > 0 %}{{ percent_iscomplete }}%</span>
                <span class="text-muted small pt-2 ps-1">от запланированных {{ proposals_isshedule_today }}{% endif %}</span>
            </div>
        </div>
    </div>
</div>

templates/templatetags/dashboard_upcoming_birthdays.html
<div class="card">
    <div class="filter">
        <a class="icon" href="#" data-bs-toggle="dropdown"><i class="bi bi-three-dots"></i></a>
        <ul class="dropdown-menu dropdown-menu-end dropdown-menu-arrow">
            <li class="dropdown-header text-start">
                <h6>Filter</h6>
            </li>
            <li><a class="dropdown-item" href="#">Today</a></li>
            <li><a class="dropdown-item" href="#">This Month</a></li>
            <li><a class="dropdown-item" href="#">This Year</a></li>
        </ul>
    </div>
    <div class="card-body">
        <h5 class="card-title">Именинники <span>| в ближайшее время</span></h5>
        <div class="activity">
            {% for item in profiles %}
                <div class="activity-item d-flex">
                    <div class="activite-label">{{ item.birthday|timeuntil:curr_date }}</div>
                    <i class='bi bi-circle-fill activity-badge text-success align-self-start'></i>
                    <div class="activity-content">
                        {{ item.user.lastname }} {{ item.user.firstname }} <small>{{ item.birthday|date:"d.m.Y" }}</small>
                    </div>
                </div><!-- End activity item-->
            {% endfor %}
        </div>
    </div>
</div><!-- End Recent Activity -->

templates/templatetags/logo.html
{% load static %}

<div class="d-flex align-items-center justify-content-between">
    <a href="{% url 'dashboard' %}" class="logo-small d-flex align-items-center">
        <img src="{% static 'img/logo.png' %}" alt="logo helpdesk pages">
    </a>
{#    <i class="bi bi-list toggle-sidebar-btn"></i>#}
</div>

templates/templatetags/maintenance_object_add.html
{% load django_bootstrap5 %}

<div class="modal fade" id="newProposal" tabindex="-1" aria-labelledby="newProposalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="newProposalLabel">Новая заявка на Эксплуатацию</h5>
            </div>
            <div class="modal-body">
                <div class="modal-body">
                    <div class="mb-3">
                        <div class="row">
                            <div class="col-4">
                                {% bootstrap_label "Объект" label_for="object_number" %}*
                            </div>
                            <div class="col-3">
                                {% bootstrap_field form.object_number layout='inline' %}
                            </div>
                            <div class="col-5">
                                {% bootstrap_field form.client_words layout='inline' %}
                            </div>
                            <div class="col-12 mt-3">
                                {% bootstrap_field form.object_address layout='inline' %}
                            </div>
                        </div>
                    </div>
                    <div class="mb-3">
                        <div class="row">
                            <div class="col-4">
                                {% bootstrap_label "Неисправность" label_for="descript_trouble" %}*
                            </div>
                            <div class="col-8">
                                {% bootstrap_field form.descript_trouble layout='inline' %}
                            </div>
                        </div>
                    </div>
                    <div class="mb-3">
                        <div class="row">
                            <div class="col-4">
                                {% bootstrap_label "Исполнитель" label_for="coworkers" %}*
                            </div>
                            <div class="col-8">
                                {% bootstrap_field form.coworkers layout='inline' %}
                            </div>
                        </div>
                    </div>
                    <div class="mb-3">
                        <div class="row">
                            <div class="col-4">
                                {% bootstrap_label "Выполнить" label_for="date_schedule" %}*
                            </div>
                            <div class="col-8">
                                {% bootstrap_field form.date_schedule layout='inline' %}
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Закрыть</button>
                <button type="submit" class="btn btn-primary">Создать запись</button>
            </div>
        </div>
    </div>
</div>

templates/templatetags/maintenance_request_add.html
{% load django_bootstrap5 %}

<div class="modal fade" id="newProposal" tabindex="-1" aria-labelledby="newProposalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="pagetitle">
                <div class="row">
                    <div class="col-4">
                        {% include 'templatetags/pagetitle_status.html' with status=status app_name=app_name.verbose_name type_document=type_document %}
                    </div>
                    <div class="col-7">
                        {% include 'templatetags/client_add.html' with form=form %}
                    </div>
                    <div class="col">
                        <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#newClient">Добавить</button>
                    </div>
                </div>
            </div>
            <div class="modal-header">
                <h5 class="modal-title" id="newProposalLabel">Новая заявка на Эксплуатацию</h5>
            </div>
            <div class="modal-body">
                <div class="modal-body">
                    <div class="mb-3">
                        <div class="row">
                            <div class="col-4">
                                {% bootstrap_label "Выполнить" label_for="date_schedule" %}*
                            </div>
                            <div class="col-8">
                                {% bootstrap_field form.date_schedule layout='inline' %}
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Закрыть</button>
                <button type="submit" class="btn btn-primary">Создать запись</button>
            </div>
        </div>
    </div>
</div>

templates/templatetags/pagetitle_status.html
<h1>{{ status }}</h1>
<nav>
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="{% url 'dashboard' %}">Панель управления</a></li>
        <li class="breadcrumb-item">{{ app_name }}</li>
        <li class="breadcrumb-item active">{{ type_document }}</li>
    </ol>
</nav>

templates/templatetags/rb_container.html
{% extends "base.html" %}
{% load dashboard_tags static base_tags %}

{% block basebody %}
    <header id="header" class="header fixed-top d-flex align-items-center">
        {% include 'templatetags/logo.html' %}
        {% include 'templatetags/searchbar.html' %}
        {% include 'templatetags/topnav.html' %}
    </header>

    <main id="main" class="main">
        <div class="container">
            <div class="row">
                <div class="col-3">
                    <div class="card">
                        <div class="card-body">
                            {% rb_menu %}
                        </div>
                    </div>
                </div>
                <div class="col-9">
                    {% block content %}{% endblock %}
                </div>
            </div>
        </div>
    </main>
{% endblock %}

templates/templatetags/rb_navigation.html
{% load mptt_tags %}

<div class="list-group list-group-flush p-3">
    {% recursetree nodes %}
        <li class="list-group-item list-group-item-action">
            <a href="/{{ node.get_root.slug }}/{{ node.slug }}/" class="nav-link">
                <i class="bi bi-grid"></i>
                <span>{{ node.name }}</span>
            </a>
            {{ children }}
        </li>
    {% endrecursetree %}
</div>

templates/templatetags/searchbar.html
<div class="search-bar">
    <form class="search-form d-flex align-items-center" method="POST" action="#">
        <input type="text" name="query" placeholder="Search" title="Enter search keyword">
        <button type="submit" title="Search"><i class="bi bi-search"></i></button>
    </form>
</div>

templates/templatetags/sidebar.html
{% load mptt_tags %}

<aside id="sidebar" class="sidebar">

    <ul class="sidebar-nav" id="sidebar-nav">
        {% if nodes %}
            {% recursetree nodes %}
                {% if node.is_root_node %}
                    <!-- если это корневой узел -->
                    {% if not node.is_leaf_node %}
                        <!-- если это не элемент -->
                        <li class="nav-item">
                            <a class="nav-link collapsed" data-bs-target="#{{ node.slug }}-nav" data-bs-toggle="collapse" href="#">
                                <i class="{{ node.class_icon }}"></i><span>{{ node.name }}</span>
                                <i class="bi bi-chevron-down ms-auto"></i>
                            </a>
                            <ul id="{{ node.slug }}-nav" class="nav-content collapse " data-bs-parent="#sidebar-nav">
                                {{ children }}
                            </ul>
                        </li>
                    {% else %}
                        <!-- если это элемент -->
                        <li class="nav-item">
                            <a href="/{{ node.slug }}/" class="nav-link">
                                <i class="bi bi-grid"></i>
                                <span>{{ node.name }}</span>
                            </a>
                            {{ children }}
                        </li>
                    {% endif %}
                {% else %}
                    <!-- если это не корневой узел -->
                    {% if node.is_leaf_node %}
                        <!-- если это элемент -->
                        <li>
                            <a href="/{{ node.get_root.slug }}/{{ node.slug }}/">
                                <i class="bi bi-circle"></i><span>{{ node.name }}</span>
                            </a>
                            {{ children }}
                        </li>
                    {% endif %}
                {% endif %}
            {% endrecursetree %}
        {% endif %}

    </ul>
</aside>

templates/templatetags/topnav.html
{% load static %}

<nav class="header-nav ms-auto">

    <ul class="d-flex align-items-center">

        <li class="nav-item pe-2">
            <a class="navbar-brand" href="{% url 'dashboard' %}">
                <img src="{% static 'img/home.png' %}" alt="find" class="d-inline-block align-text-top">
            </a>
        </li>
        <li class="nav-item pe-4">
            <a class="navbar-brand" href="#">
                <img src="{% static 'img/find.png' %}" alt="find" class="d-inline-block align-text-top">
            </a>
        </li>
        <li class="nav-item pe-2">
            <a class="navbar-brand" href="{% url 'exploitation:getlist-proposals' 'open' %}">
                <img src="{% static 'img/bug.png' %}" alt="exploitation-app" class="d-inline-block align-text-top">
            </a>
        </li>
        <li class="nav-item pe-4">
            <a class="navbar-brand" href="{% url 'build:getlist-proposals' 'open' %}">
                <img src="{% static 'img/hammer.png' %}" alt="build-app" class="d-inline-block align-text-top">
            </a>
        </li>
        <li class="nav-item pe-4">
            <a class="navbar-brand" href="{% url 'maintenance:getlist-proposals' 'open' %}">
                <img src="{% static 'img/tools.png' %}" alt="maintenance-app" class="d-inline-block align-text-top">
            </a>
        </li>
        <li class="nav-item pe-3">
            <a class="navbar-brand" href="{% url 'base:getlist-clients' %}">
                <img src="{% static 'img/library.png' %}" alt="library-app" class="d-inline-block align-text-top">
            </a>
        </li>

        {% if user.profile.list_scompany|length > 1 %}
            <li class="nav-item dropdown pe-5">
                <a class="nav-link dropdown-toggle" data-bs-toggle="dropdown" href="#" role="button" aria-expanded="false">{{ user.profile.current_scompany }}</a>
                <ul class="dropdown-menu">
                    {% for item in user.profile.list_scompany %}
                        <li><a class="dropdown-item {% if item.pk == user.profile.current_scompany.pk %}disabled{% endif %}" href="{% url 'base:change-service-company' item.pk %}">{{ item.name }}</a></li>
                    {% endfor %}
                </ul>
            </li>
        {% endif %}

        <li class="nav-item dropdown pe-3">
            <a class="nav-link nav-profile d-flex align-items-center pe-0" href="#" data-bs-toggle="dropdown">
                <img src="{% static 'img/profile-img.jpg' %}" alt="Profile" class="rounded-circle">
                <span class="d-none d-md-block dropdown-toggle ps-2">{{ user.first_name|truncatechars:2 }} {{ user.last_name }}</span>
            </a><!-- End Profile Iamge Icon -->

            <ul class="dropdown-menu dropdown-menu-end dropdown-menu-arrow profile">
                <li class="dropdown-header">
                    <h6>{{ user.profile.short_fio }}</h6>
                    <span>{{ user.profile.post }}</span>
                </li>
                <li>
                    <hr class="dropdown-divider">
                </li>
                <li>
                    <a class="dropdown-item d-flex align-items-center" href="#">
                        <i class="bi bi-briefcase"></i>
                        <span>{{ user.profile.current_scompany }}</span>
                    </a>
                </li>
                <li>
                    <hr class="dropdown-divider">
                </li>
                <li>
                    <a class="dropdown-item d-flex align-items-center" href="#">
                        <i class="bi bi-person"></i>
                        <span>Мой профиль</span>
                    </a>
                </li>
                <li>
                  <hr class="dropdown-divider">
                </li>
                <li>
                  <a class="dropdown-item d-flex align-items-center" href="#">
                    <i class="bi bi-question-circle"></i>
                    <span>Нужна помощь?</span>
                  </a>
                </li>
                <li>
                  <hr class="dropdown-divider">
                </li>
                <li>
                  <a class="dropdown-item d-flex align-items-center" href="{% url 'logout' %}">
                    <i class="bi bi-box-arrow-right"></i>
                    <span>Выйти</span>
                  </a>
                </li>

          </ul><!-- End Profile Dropdown Items -->
        </li><!-- End Profile Nav -->

      </ul>
    </nav>