base/urls.py
from django.urls import path

from base.views import ClientList, ClientUpdate, RoutList, RoutUpdate, change_service_company

app_name = 'base'

urlpatterns = [
    path('change-service-company/<int:pk>/', change_service_company, name='change-service-company'),

    # Контрагенты
    path('reference_books/clients/<int:pk>/update/', ClientUpdate.as_view(), name='upd-client'),
    path('reference_books/clients/', ClientList.as_view(), name='getlist-clients'),

    # Маршруты
    path('reference_books/routs/<int:pk>/update/', RoutUpdate.as_view(), name='upd-rout'),
    path('reference_books/routs/', RoutList.as_view(), name='getlist-routs'),
]

helpdesk/urls.py
from django.contrib import admin
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path, reverse_lazy, include
from django.conf import settings
from django.conf.urls.static import static

from base.views import *

urlpatterns = [
    path('admin/', admin.site.urls),

    path(r'accounts/login/', CustomLoginPage.as_view(), name='login'),
    path('accounts/logout', LogoutView.as_view(next_page=reverse_lazy('login')), name='logout'),
    # path('accounts/profile/', , name='profile'),

    # path('finder/', advanced_finder, name='advanced-finder'),

    path('base/', include('base.urls', namespace='base')),

    path('exploitation/', include('exploitation.urls', namespace='exploitation')),
    path('build/', include('build.urls', namespace='build')),
    path('maintenance/', include('maintenance.urls', namespace='maintenance')),

    path('', dashboard, name='dashboard'),
]

maintenance/urls.py
__author__ = 'ipman'

from django.urls import path

from maintenance.views import *

app_name = 'maintenance'

urlpatterns = [
    # Просмотреть объект
    path('objects/<int:pk>/detail/', MaintenanceObjectDetail.as_view(), name='view-object'),
    # Просмотреть заявку
    path('item/<int:pk>/detail/', MaintenanceProposalDetail.as_view(), name='view-proposal'),
    # Обновить заявку
    path('item/<int:pk>/update/', MaintenanceProposalUpdate.as_view(), name='upd-manage-proposal'),
    # Вывести список заявок
    path('objects/<slug:status>/', MaintenanceObjectList.as_view(), name='getlist-objects'),
    path('proposal/<slug:status>/', MaintenanceProposalList.as_view(), name='getlist-proposals'),
]

maintenance/models.py
from django.db import models
from django_currentuser.db.models import CurrentUserField

from base.models import Client, TypeSecurity, MonthList, ServiceCompany, Status, \
    RoutesMaintenance, TypeRequest, TypeDocument, Profile


def maintenance_type_request():
    return TypeRequest.objects.get(slug='maintenance')


def maintenance_type_document_object():
    return TypeDocument.objects.get(slug='object')


class MaintenanceObject(models.Model):
    service_company = models.ForeignKey(ServiceCompany, verbose_name='Организация', on_delete=models.CASCADE)

    type_request = models.ForeignKey(TypeRequest, models.SET_NULL, verbose_name='Тип заявки',
                                     default=maintenance_type_request, null=True)
    type_document = models.ForeignKey(TypeDocument, models.SET_NULL, verbose_name='Тип документа',
                                      default=maintenance_type_document_object, null=True)
    type_security = models.ManyToManyField(TypeSecurity, verbose_name='Тип сигнализации',
                                           help_text="Выбор нескольких позиций c нажатой кнопкой Ctrl")

    object_address = models.CharField(u'Адрес объекта', max_length=300)

    client_choices = models.ForeignKey(Client, models.SET_NULL, verbose_name='Контрагент', blank=True, null=True,
                                       help_text="Обязательно для заполнения перед закрытием заявки")

    rout = models.ForeignKey(RoutesMaintenance, models.SET_NULL, verbose_name=u'Маршрут', null=True, blank=True)

    month_schedule = models.ManyToManyField(MonthList, verbose_name=u'Месяцы обслуживания',
                                           help_text=u'Выбор нескольких позиций c нажатой кнопкой Ctrl', blank=True)

    date_start = models.DateField(u'Дата начала обслуживания')
    date_end = models.DateField(u'Дата окончания обслуживания', help_text=u'Указываем последний день обслуживания',
                                null=True, blank=True)

    status = models.BooleanField(Status, u'Обслуживается', default=False, null=True)

    date_time_add = models.DateTimeField(u'Дата и время добавления', auto_now_add=True)
    date_time_upd = models.DateTimeField(u'Дата и время обновления', auto_now=True)

    create_user = CurrentUserField(on_update=False, related_name='mo_creator')
    update_user = CurrentUserField(on_update=True, related_name='mo_modifying')

    def __str__(self):
        return self.object_address

    class Meta:
        app_label = 'maintenance'
        verbose_name = u'Объект '
        verbose_name_plural = u'Список объектов ТО '
        permissions = (
            ('custom_add_object', u'Добавить объект'),
            ('custom_view_object', u'Просмотреть объект'),
            ('custom_change_object', u'Изменить объект'),
        )


def maintenance_type_document_request():
    return TypeDocument.objects.get(slug='request')


class MaintenanceProposal(models.Model):
    type_request = models.ForeignKey(TypeRequest, models.SET_NULL, verbose_name='Тип заявки',
                                     default=maintenance_type_request, null=True)
    type_document = models.ForeignKey(TypeDocument, models.SET_NULL, verbose_name='Тип документа',
                                      default=maintenance_type_document_object, null=True)

    object = models.ForeignKey(MaintenanceObject, verbose_name=u'Объект', on_delete=models.CASCADE)

    date_schedule = models.DateField(u'Запланировано', null=True, blank=True)
    date_work = models.DateField(u'Дата исполнения', null=True, blank=True)

    descript_work = models.TextField(u'Что сделали', blank=True)

    coworkers = models.ManyToManyField(Profile, verbose_name='Исполнитель', blank=True)

    status = models.ForeignKey(Status, models.SET_NULL, verbose_name='Статус заявки',
                               default=maintenance_type_document_request, null=True)

    date_time_add = models.DateTimeField(u'Дата и время добавления', auto_now_add=True)
    date_time_upd = models.DateTimeField(u'Дата и время обновления', auto_now=True)

    create_user = CurrentUserField(on_update=False, related_name='mp_creator')
    update_user = CurrentUserField(on_update=True, related_name='mp_modifying')

    def __str__(self):
        return self.object.object_address

    class Meta:
        app_label = 'maintenance'
        verbose_name = u'Заявка '
        verbose_name_plural = u'Список заявок ТО'
        permissions = (
            ('custom_add', u'Добавить заявку ТО'),
            ('custom_view', u'Просмотреть заявку ТО'),
            ('custom_change', u'Изменить заявку ТО'),
        )

maintenance/forms.py
from django.utils import timezone
from django import forms
from django.forms import ModelForm

from easy_select2 import Select2Multiple

from maintenance.models import MaintenanceObject, MaintenanceProposal
from helpdesk.widgets import SelectWidget
from base.models import Profile, Status


class MaintenanceObjectCreateForm(ModelForm):

    def __init__(self, *args, **kwargs):
        super(MaintenanceObjectCreateForm, self).__init__(*args, **kwargs)
        self.user = kwargs['initial'].pop('user', None)

    object_address = forms.CharField(label=u'Адрес объекта',
                                     widget=forms.widgets.TextInput(attrs={'id': 'id_AddressObject',
                                                                           'style': 'padding: 0px'}))

    class Meta:
        model = MaintenanceObject
        fields = ['object_address', 'client_choices', 'rout', 'month_schedule', 'date_start', 'date_end']


class MaintenanceObjectUpdateManagerForm(ModelForm):

    def __init__(self, *args, **kwargs):
        super(MaintenanceObjectUpdateManagerForm, self).__init__(*args, **kwargs)
        instance = getattr(self, 'instance', None)
        self.user = kwargs['initial'].pop('user', None)

    status = forms.ModelChoiceField(required=False, label='Состояние', widget=SelectWidget,
                                    queryset=Status.objects.all())

    class Meta:
        model = MaintenanceObject
        fields = ['client_choices', 'rout', 'month_schedule', 'date_start', 'date_end', 'status']


class MaintenanceProposalCreateForm(ModelForm):

    class Meta:
        model = MaintenanceProposal
        fields = ['date_schedule']


class MaintenanceProposalUpdateManagerForm(ModelForm):

    def __init__(self, *args, **kwargs):
        super(MaintenanceProposalUpdateManagerForm, self).__init__(*args, **kwargs)
        instance = getattr(self, 'instance', None)
        self.user = kwargs['initial'].pop('user', None)

        self.fields['status'].queryset = Status.objects.exclude(slug__in=['scheduled']).order_by('id')
        self.fields['status'].widget.disabled_choices = [1, 3]
        self.fields['coworkers'].queryset = self.profile.executors

    date_schedule = forms.DateField(required=False, label='Выполнить', input_formats=('%Y-%m-%d',),
                                    widget=forms.DateInput(format='%Y-%m-%d', attrs={'type': 'date'}),)
    date_work = forms.DateField(required=False, label='Выполнено', input_formats=('%Y-%m-%d',),
                                widget=forms.DateInput(format='%Y-%m-%d', attrs={'type': 'date'}),)
    descript_work = forms.CharField(required=False, label='Описание выполненных работ',
                                    widget=forms.widgets.Textarea(attrs={'rows': 5}))
    status = forms.ModelChoiceField(required=False, label='Состояние', widget=SelectWidget,
                                    queryset=Status.objects.all())
    coworkers = forms.ModelMultipleChoiceField(required=False, label='Исполнители', queryset=Profile.objects.all(),
                                               widget=Select2Multiple())

    class Meta:
        model = MaintenanceProposal
        fields = ['date_schedule', 'descript_work', 'date_work', 'coworkers', 'status']

maintenance/views.py
import logging

from datetime import datetime
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import get_object_or_404
from django.urls import reverse_lazy
from django.views.generic import FormView, UpdateView, DetailView
from django.views.generic.list import ListView

from base.models import Event, Status, Profile
from maintenance.apps import MaintenanceConfig
from maintenance.forms import *
from maintenance.models import *


logger = logging.getLogger(__name__)

events = Event.objects.all()

app = MaintenanceConfig.name
app_name = 'Техническое обслуживание'


class MaintenanceObjectList(LoginRequiredMixin, ListView, FormView):
    template_name = "maintenance/maintenance_object_list.html"
    model = MaintenanceObject
    form_class = MaintenanceObjectCreateForm
    success_url = reverse_lazy('maintenance:getlist_objects', args=['open'])
    paginate_by = 5

    def get_form_kwargs(self):
        kwargs = super(MaintenanceObjectList, self).get_form_kwargs()
        kwargs.update({'initial': {'user': self.request.user}})
        return kwargs

    def get_context_data(self, **kwargs):
        context = super(MaintenanceObjectList, self).get_context_data(**kwargs)
        curr_status = self.kwargs['status'] if self.kwargs['status'] else 'open'
        context["status"] = Status.objects.get(slug=curr_status)
        context["app_name"] = app_name
        context["type_document"] = "Заявки"
        context["list_status"] = Status.objects.exclude(slug=curr_status)
        return context

    def get_queryset(self, **kwargs):
        proposals = MaintenanceObject.objects.filter(service_company=self.request.user.profile.current_scompany)
        if self.kwargs['status'] == 'open':
            qs = proposals.filter(status__slug__in=['open', 'complete'], date_schedule__lte=datetime.today())
        elif self.kwargs['status'] == 'scheduled':
            qs = proposals.filter(status__slug__in=['open', 'complete'], date_schedule__gt=datetime.today())
        else:
            qs = proposals.filter(status__slug=self.kwargs['status'], date_schedule__year=datetime.today().year)
        return qs

    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.service_company = Profile.objects.get(user=self.request.user).current_scompany
        self.object.save()
        return super(MaintenanceObjectList, self).form_valid(form)

    def form_invalid(self, form):
        return self.render_to_response(self.get_context_data(form=form, context_key='Form is not valid'))


class MaintenanceObjectUpdate(LoginRequiredMixin, UpdateView):
    model = MaintenanceObject
    template_name = 'maintenance/maintenance_object_upd.html'
    form_class = MaintenanceObjectUpdateManagerForm
    # success_url = reverse_lazy('close_tab')

    def get_form_kwargs(self):
        kwargs = super(MaintenanceObjectUpdate, self).get_form_kwargs()
        kwargs.update({'initial': {'user': self.request.user}})
        return kwargs

    def get_context_data(self, **kwargs):
        context = super(MaintenanceObjectUpdate, self).get_context_data(**kwargs)
        proposal = get_object_or_404(MaintenanceObject, pk=self.kwargs['pk'])
        context["app_name"] = app_name
        context["proposal"] = proposal
        return context

    def form_valid(self, form):
        return super().form_valid(form)

    def form_invalid(self, form):
        return self.render_to_response(self.get_context_data(form=form, context_key='Form is not valid'))


class MaintenanceObjectDetail(LoginRequiredMixin, DetailView):
    model = MaintenanceObject
    template_name = 'maintenance/maintenance_object_detail.html'

    def get_context_data(self, **kwargs):
        context = super(MaintenanceObjectDetail, self).get_context_data(**kwargs)
        proposal = get_object_or_404(MaintenanceProposalDetail, pk=self.kwargs['pk'])
        context["proposal"] = proposal
        return context


class MaintenanceProposalList(LoginRequiredMixin, ListView, FormView):
    template_name = "maintenance/maintenance_proposal_list.html"
    model = MaintenanceProposal
    form_class = MaintenanceProposalCreateForm
    success_url = reverse_lazy('maintenance:getlist_proposals', args=['open'])
    paginate_by = 5

    def get_form_kwargs(self):
        kwargs = super(MaintenanceProposalList, self).get_form_kwargs()
        kwargs.update({'initial': {'user': self.request.user}})
        return kwargs

    def get_context_data(self, **kwargs):
        context = super(MaintenanceProposalList, self).get_context_data(**kwargs)
        curr_status = self.kwargs['status'] if self.kwargs['status'] else 'open'
        context["status"] = Status.objects.get(slug=curr_status)
        context["app_name"] = app_name
        context["type_document"] = "Заявки"
        context["list_status"] = Status.objects.exclude(slug=curr_status)
        return context

    def get_queryset(self, **kwargs):
        proposals = MaintenanceProposal.objects.filter(object__service_company=self.request.user.profile.current_scompany)
        if self.kwargs['status'] == 'open':
            qs = proposals.filter(status__slug__in=['open', 'complete'], date_schedule__lte=datetime.today())
        elif self.kwargs['status'] == 'scheduled':
            qs = proposals.filter(status__slug__in=['open', 'complete'], date_schedule__gt=datetime.today())
        else:
            qs = proposals.filter(status__slug=self.kwargs['status'], date_schedule__year=datetime.today().year)
        return qs

    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.service_company = Profile.objects.get(user=self.request.user).current_scompany
        self.object.save()
        return super(MaintenanceProposalList, self).form_valid(form)

    def form_invalid(self, form):
        return self.render_to_response(self.get_context_data(form=form, context_key='Form is not valid'))


class MaintenanceProposalUpdate(LoginRequiredMixin, UpdateView):
    model = MaintenanceProposal
    template_name = 'maintenance/maintenance_proposal_upd.html'
    form_class = MaintenanceProposalUpdateManagerForm
    # success_url = reverse_lazy('close_tab')

    def get_form_kwargs(self):
        kwargs = super(MaintenanceProposalUpdate, self).get_form_kwargs()
        kwargs.update({'initial': {'user': self.request.user}})
        return kwargs

    def get_context_data(self, **kwargs):
        context = super(MaintenanceProposalUpdate, self).get_context_data(**kwargs)
        proposal = get_object_or_404(MaintenanceProposal, pk=self.kwargs['pk'])
        context["app_name"] = app_name
        context["proposal"] = proposal
        return context

    def form_valid(self, form):
        return super().form_valid(form)

    def form_invalid(self, form):
        return self.render_to_response(self.get_context_data(form=form, context_key='Form is not valid'))


class MaintenanceProposalDetail(LoginRequiredMixin, DetailView):
    model = MaintenanceProposal
    template_name = 'maintenance/maintenance_proposal_detail.html'

    def get_context_data(self, **kwargs):
        context = super(MaintenanceProposalDetail, self).get_context_data(**kwargs)
        proposal = get_object_or_404(MaintenanceProposalDetail, pk=self.kwargs['pk'])
        context["proposal"] = proposal
        return context

templates/maintenance/maintenance_object_list.html
{% extends 'page_content_fluid.html' %}
{% load exploitation_tags %}

{% block tab_title %}Список объектов{% endblock %}
{% block content %}
    <main id="main" class="main">
        <div class="pagetitle">
            <div class="row">
                <div class="col-4">
                    {% include 'templatetags/pagetitle_status.html' with status=status app_name=app_name.verbose_name type_document=type_document %}
                </div>
                <div class="col-7">
                    <ul class="nav">
                        {% for item in list_status %}
                            <li class="nav-item">
                                <a class="nav-link" aria-current="page" href="{% url 'maintenance:getlist-objects' item.slug %}">{{ item.name }}</a>
                            </li>
                        {% endfor %}
                    </ul>
{#                    {% include 'templatetags/maintenance_object_add.html' with form=form %}#}
                </div>
                <div class="col">
                    <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#newProposal">Добавить</button>
                </div>
            </div>
        </div>
        <section class="section">
            <div class="row">
                <div class="col-lg-12">
                    <div class="card">
                        <div class="card-body">
                            <h5 class="card-title pt-sm-1"></h5>
                            <table class="table table-sm datatable">
                                {% if object_list %}
                                    <thead>
                                        <tr class="text-center">
                                            <th scope="col">#</th>
                                            <th scope="col">Добавлено</th>
                                            <th scope="col">Объект</th>
                                            <th scope="col">Контрагент</th>
                                            <th scope="col">Период</th>
                                            <th scope="col">Статус</th>
                                        </tr>
                                    </thead>
                                {% endif %}
                                <tbody>
                                    {% for item in object_list %}
                                        <tr id="obj_{{ item.id }}" target="_blank" onclick="javascript:window.open('#')">
                                            <th scope="row">{{ item.id }}</th>
                                            <td class="text-center">
                                                {{ item.date_time_add|date:"d.m" }}<br/>
                                                {{ item.date_time_add|date:"H:i" }}
                                            </td>
                                            <td>{{ item.object_number }} - {{ item.object_address }}</td>
                                            <td>
                                                {% if client_choices %}
                                                    {{ item.client_choices.name }}
                                                {% else %}
                                                    {{ item.client_words }}
                                                {% endif %}
                                            </td>
                                            <td class="text-center">
                                                {{ item.date_start|date:"d.m" }} - {{ item.date_end|date:"d.m" }}
                                            </td>
                                            <td class="text-center">{{ item.status }}</td>
                                        </tr>
                                    {% endfor %}
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </section>
    </main>
{% endblock %}

templates/maintenance/maintenance_object_upd.html
{% extends 'page_content_fluid.html' %}
{% load static django_bootstrap5 %}

{% block include_header %}
    <style>
        .form-group {
            margin-bottom: .5rem;
        }
        .card-columns {
            -webkit-column-count:1;
            -moz-column-count:1;
            column-count:1;
        }
        .card-body {
            padding:.5rem 1rem 1.2rem 1rem;
        }
    </style>
    <link href="{% static "css/suggestions-15.12.css" %}" rel="stylesheet" type="text/css"/>
    <link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/css/select2.min.css" rel="stylesheet" />
    <script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js"></script>
{% endblock %}

{% block tab_title %}Заявка{% endblock %}
{% block content %}
    <main id="main" class="main">
        <div class="pagetitle">
            <div class="row">
                <div class="col-4">
                    <h1>Заявка #{{ proposal.pk }}</h1>
                    <nav>
                        <ol class="breadcrumb">
                            <li class="breadcrumb-item"><a href="{% url 'dashboard' %}">Панель управления</a></li>
                            <li class="breadcrumb-item">{{ app_name.verbose_name }}</li>
                            <li class="breadcrumb-item active">{{ proposal.type_document.name }}</li>
                        </ol>
                    </nav>
                </div>
                <div class="col-8">
                    <ul class="nav">
                        {% for item in list_status %}
                            <li class="nav-item">
                                <a class="nav-link active" aria-current="page" href="{% url 'exploitation:getlist-proposals' item.slug %}">{{ item.name }}</a>
                            </li>
                        {% endfor %}
                    </ul>
                </div>
            </div>
        </div>
        <section class="section container">
            <div class="row">
                <div class="col-4 p-10">
                    <div class="card-columns">
                        <div class="card">
                            <div class="card-body">
                                <h6 class="card-title">Объект</h6>
                                <p class="h5">{{ proposal.client_words }}</p>
                                <p class="card-text">{{ proposal.object_number }} ({{ proposal.object_address }})</p>
                            </div>
                        </div>
                        <div class="card">
                            <div class="card-body">
                                <h6 class="card-title">Описание неисправности</h6>
                                <p class="card-text overflow-auto">{{ proposal.descript_troubles }}</p>
                            </div>
                        </div>
                        <div class="card">
                            <div class="card-body">
                                <h6 class="card-title">Добавлено</h6>
                                <p class="card-text overflow-auto">{{ proposal.create_user }} <small>{{ proposal.date_time_add|date:"d.m.Y" }}</small></p>
                            </div>
                        </div>
                        <div class="card">
                            <div class="card-body">
                                <h6 class="card-title">Обновлено</h6>
                                <p class="card-text overflow-auto">{{ proposal.update_user }} <small>{{ proposal.date_time_upd|date:"d.m.Y" }}</small></p>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-8 p-10">
                    <div class="row">
                        <div class="card">
                            {% bootstrap_form_errors form %}
                            <form action="{% url 'exploitation:upd-manage-proposal' proposal.pk %}" method="post" class="form">{% csrf_token %}
                                <div class="card-body mt-4">
                                    <div class="mb-3">
                                        <div class="row">
                                            <div class="col-3">
                                                {% bootstrap_label "Даты" label_for="date_schedule" %}
                                            </div>
                                            <div class="col-9">
                                                {% bootstrap_field form.date_schedule layout='horizontal' %}
                                            </div>
                                            <div class="col-9 offset-3">
                                                {% bootstrap_field form.date_work layout='horizontal' %}
                                            </div>
                                        </div>
                                    </div>
                                    <div class="mb-3">
                                        <div class="row">
                                            <div class="col-3">
                                                {% bootstrap_label "Описание исполнения" label_for="descript_work" %}
                                            </div>
                                            <div class="col-9">
                                                {% bootstrap_field form.descript_work layout='inline' %}
                                            </div>
                                        </div>
                                    </div>
                                    <div class="mb-3">
                                        <div class="row">
                                            <div class="col-3">
                                                {% bootstrap_label "Исполнители" label_for="coworkers" %}
                                            </div>
                                            <div class="col-9">
                                                {% bootstrap_field form.coworkers layout='inline' %}
                                            </div>
                                        </div>
                                    </div>
                                    {% bootstrap_field form.status layout='horizontal' %}
                                    <div class="mb-3">
                                        <div class="row">
                                            <div class="col-3">
                                                {% bootstrap_label "Акт" label_for="required_act" %}
                                            </div>
                                            {% if proposal.written_act %}
                                                <div class="col-6">
                                                    Акт выписан от {{ date_act }}
                                                </div>
                                            {% else %}
                                                <div class="col-4">
                                                    {% bootstrap_field form.required_act layout='inline' %}
                                                </div>
                                                <div class="col-4">
                                                    {% bootstrap_field form.date_act layout='inline' %}
                                                </div>
                                            {% endif %}
                                        </div>
                                    </div>
                                </div>
                                <div class="card-footer">
                                    <div class="row">
                                        <div class="col-4">
                                            <a type="button" class="btn btn-secondary" href="#">Закрыть заявку</a>
                                        </div>
                                        <div class="col-4 offset-4">
                                            {% if perms.custom_add and perms.custom_change %}
                                                {% bootstrap_button "Сохранить изменения" button_type="submit" button_class="btn-primary" %}
                                            {% endif %}
                                        </div>
                                    </div>
                                </div>
                            </form>
                            <script>
                                $(document).ready(function (){
                                    $('#id_coworkers').select2();
                                })
                            </script>
                        </div>
                    </div>
                </div>
            </div>
        </section>
    </main>
{% endblock %}